### ISSUE TITLE
Issue running sentiment.py

### ISSUE THREAD

**Issue by charlesaugdupont** [nik0spapp/usent#2]
When I try running sentiment.py, I obtain the following error:

 .../hp_classifiers.py in classify(self, sentence)
     38         subjective = False
     39         for word in words:
---> 40             word = word.lower()
     41             check = [stemmer.stem(word)]
     42             for w in check:

NameError: global name 'stem' is not defined

I am not sure what is causing this. Could anyone lend me a hand?

I also seem to have an issue with the line 
`from stemming.porter2 import stem` 

(ImportError: No module named stemming.porter2)

**Comment by charlesaugdupont** [comment]
Running python setup.py build on PyMl version 0.7.11 yielded this error:

PyML/classifiers/ext/KNN.cpp:4:14: error: addition of default argument on redeclaration makes this constructor a default constructor
KNN::KNN(int _k = 3) : k(_k)
             ^    ~
PyML/classifiers/ext/KNN.h:15:5: note: previous declaration is here
    KNN(int k);
    ^
1 error generated.
error: command 'gcc' failed with exit status 1

**Comment by charlesaugdupont** [comment]
All I had to do was run pip2 install stemming. Issue resolved!

The pip install stemmer for some reason did not work for me.

**Comment by nik0spapp** [comment]
Thanks for the feedback!
